/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashRouteImport } from './routes/dash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashIndexRouteImport } from './routes/dash/index'
import { Route as DashSettingsRouteImport } from './routes/dash/settings'
import { Route as DashRequestsRouteImport } from './routes/dash/requests'
import { Route as DashInstallRouteImport } from './routes/dash/install'
import { Route as ApiAuthTokensRouteImport } from './routes/api/auth-tokens'
import { Route as DashTunnelsIndexRouteImport } from './routes/dash/tunnels/index'
import { Route as ApiTunnelsIndexRouteImport } from './routes/api/tunnels/index'
import { Route as DashTunnelsTunnelIdRouteImport } from './routes/dash/tunnels/$tunnelId'
import { Route as ApiTunnelsTunnelIdRouteImport } from './routes/api/tunnels/$tunnelId'
import { Route as ApiTunnelRegisterRouteImport } from './routes/api/tunnel/register'
import { Route as ApiTunnelCheckSubdomainRouteImport } from './routes/api/tunnel/check-subdomain'
import { Route as ApiTunnelAuthRouteImport } from './routes/api/tunnel/auth'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashRoute,
} as any)
const DashRequestsRoute = DashRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashRoute,
} as any)
const DashInstallRoute = DashInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => DashRoute,
} as any)
const ApiAuthTokensRoute = ApiAuthTokensRouteImport.update({
  id: '/api/auth-tokens',
  path: '/api/auth-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const DashTunnelsIndexRoute = DashTunnelsIndexRouteImport.update({
  id: '/tunnels/',
  path: '/tunnels/',
  getParentRoute: () => DashRoute,
} as any)
const ApiTunnelsIndexRoute = ApiTunnelsIndexRouteImport.update({
  id: '/api/tunnels/',
  path: '/api/tunnels/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashTunnelsTunnelIdRoute = DashTunnelsTunnelIdRouteImport.update({
  id: '/tunnels/$tunnelId',
  path: '/tunnels/$tunnelId',
  getParentRoute: () => DashRoute,
} as any)
const ApiTunnelsTunnelIdRoute = ApiTunnelsTunnelIdRouteImport.update({
  id: '/api/tunnels/$tunnelId',
  path: '/api/tunnels/$tunnelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelRegisterRoute = ApiTunnelRegisterRouteImport.update({
  id: '/api/tunnel/register',
  path: '/api/tunnel/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelCheckSubdomainRoute = ApiTunnelCheckSubdomainRouteImport.update({
  id: '/api/tunnel/check-subdomain',
  path: '/api/tunnel/check-subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelAuthRoute = ApiTunnelAuthRouteImport.update({
  id: '/api/tunnel/auth',
  path: '/api/tunnel/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dash': typeof DashRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/api/auth-tokens': typeof ApiAuthTokensRoute
  '/dash/install': typeof DashInstallRoute
  '/dash/requests': typeof DashRequestsRoute
  '/dash/settings': typeof DashSettingsRoute
  '/dash/': typeof DashIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/tunnels/$tunnelId': typeof ApiTunnelsTunnelIdRoute
  '/dash/tunnels/$tunnelId': typeof DashTunnelsTunnelIdRoute
  '/api/tunnels': typeof ApiTunnelsIndexRoute
  '/dash/tunnels': typeof DashTunnelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/api/auth-tokens': typeof ApiAuthTokensRoute
  '/dash/install': typeof DashInstallRoute
  '/dash/requests': typeof DashRequestsRoute
  '/dash/settings': typeof DashSettingsRoute
  '/dash': typeof DashIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/tunnels/$tunnelId': typeof ApiTunnelsTunnelIdRoute
  '/dash/tunnels/$tunnelId': typeof DashTunnelsTunnelIdRoute
  '/api/tunnels': typeof ApiTunnelsIndexRoute
  '/dash/tunnels': typeof DashTunnelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dash': typeof DashRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/api/auth-tokens': typeof ApiAuthTokensRoute
  '/dash/install': typeof DashInstallRoute
  '/dash/requests': typeof DashRequestsRoute
  '/dash/settings': typeof DashSettingsRoute
  '/dash/': typeof DashIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/tunnels/$tunnelId': typeof ApiTunnelsTunnelIdRoute
  '/dash/tunnels/$tunnelId': typeof DashTunnelsTunnelIdRoute
  '/api/tunnels/': typeof ApiTunnelsIndexRoute
  '/dash/tunnels/': typeof DashTunnelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dash'
    | '/login'
    | '/onboarding'
    | '/api/auth-tokens'
    | '/dash/install'
    | '/dash/requests'
    | '/dash/settings'
    | '/dash/'
    | '/api/auth/$'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/tunnels/$tunnelId'
    | '/dash/tunnels/$tunnelId'
    | '/api/tunnels'
    | '/dash/tunnels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/api/auth-tokens'
    | '/dash/install'
    | '/dash/requests'
    | '/dash/settings'
    | '/dash'
    | '/api/auth/$'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/tunnels/$tunnelId'
    | '/dash/tunnels/$tunnelId'
    | '/api/tunnels'
    | '/dash/tunnels'
  id:
    | '__root__'
    | '/'
    | '/dash'
    | '/login'
    | '/onboarding'
    | '/api/auth-tokens'
    | '/dash/install'
    | '/dash/requests'
    | '/dash/settings'
    | '/dash/'
    | '/api/auth/$'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/tunnels/$tunnelId'
    | '/dash/tunnels/$tunnelId'
    | '/api/tunnels/'
    | '/dash/tunnels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAuthTokensRoute: typeof ApiAuthTokensRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTunnelAuthRoute: typeof ApiTunnelAuthRoute
  ApiTunnelCheckSubdomainRoute: typeof ApiTunnelCheckSubdomainRoute
  ApiTunnelRegisterRoute: typeof ApiTunnelRegisterRoute
  ApiTunnelsTunnelIdRoute: typeof ApiTunnelsTunnelIdRoute
  ApiTunnelsIndexRoute: typeof ApiTunnelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/': {
      id: '/dash/'
      path: '/'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/settings': {
      id: '/dash/settings'
      path: '/settings'
      fullPath: '/dash/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/requests': {
      id: '/dash/requests'
      path: '/requests'
      fullPath: '/dash/requests'
      preLoaderRoute: typeof DashRequestsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/install': {
      id: '/dash/install'
      path: '/install'
      fullPath: '/dash/install'
      preLoaderRoute: typeof DashInstallRouteImport
      parentRoute: typeof DashRoute
    }
    '/api/auth-tokens': {
      id: '/api/auth-tokens'
      path: '/api/auth-tokens'
      fullPath: '/api/auth-tokens'
      preLoaderRoute: typeof ApiAuthTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/tunnels/': {
      id: '/dash/tunnels/'
      path: '/tunnels'
      fullPath: '/dash/tunnels'
      preLoaderRoute: typeof DashTunnelsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/api/tunnels/': {
      id: '/api/tunnels/'
      path: '/api/tunnels'
      fullPath: '/api/tunnels'
      preLoaderRoute: typeof ApiTunnelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/tunnels/$tunnelId': {
      id: '/dash/tunnels/$tunnelId'
      path: '/tunnels/$tunnelId'
      fullPath: '/dash/tunnels/$tunnelId'
      preLoaderRoute: typeof DashTunnelsTunnelIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/api/tunnels/$tunnelId': {
      id: '/api/tunnels/$tunnelId'
      path: '/api/tunnels/$tunnelId'
      fullPath: '/api/tunnels/$tunnelId'
      preLoaderRoute: typeof ApiTunnelsTunnelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/register': {
      id: '/api/tunnel/register'
      path: '/api/tunnel/register'
      fullPath: '/api/tunnel/register'
      preLoaderRoute: typeof ApiTunnelRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/check-subdomain': {
      id: '/api/tunnel/check-subdomain'
      path: '/api/tunnel/check-subdomain'
      fullPath: '/api/tunnel/check-subdomain'
      preLoaderRoute: typeof ApiTunnelCheckSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/auth': {
      id: '/api/tunnel/auth'
      path: '/api/tunnel/auth'
      fullPath: '/api/tunnel/auth'
      preLoaderRoute: typeof ApiTunnelAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashRouteChildren {
  DashInstallRoute: typeof DashInstallRoute
  DashRequestsRoute: typeof DashRequestsRoute
  DashSettingsRoute: typeof DashSettingsRoute
  DashIndexRoute: typeof DashIndexRoute
  DashTunnelsTunnelIdRoute: typeof DashTunnelsTunnelIdRoute
  DashTunnelsIndexRoute: typeof DashTunnelsIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashInstallRoute: DashInstallRoute,
  DashRequestsRoute: DashRequestsRoute,
  DashSettingsRoute: DashSettingsRoute,
  DashIndexRoute: DashIndexRoute,
  DashTunnelsTunnelIdRoute: DashTunnelsTunnelIdRoute,
  DashTunnelsIndexRoute: DashTunnelsIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAuthTokensRoute: ApiAuthTokensRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTunnelAuthRoute: ApiTunnelAuthRoute,
  ApiTunnelCheckSubdomainRoute: ApiTunnelCheckSubdomainRoute,
  ApiTunnelRegisterRoute: ApiTunnelRegisterRoute,
  ApiTunnelsTunnelIdRoute: ApiTunnelsTunnelIdRoute,
  ApiTunnelsIndexRoute: ApiTunnelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
